version: "3"
services:
  web:
    build: .
    command: ./wait-for.sh mongo:27017 -- npm start
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge

      